# Generated by Django 3.0.4 on 2020-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
